# -*- coding: utf-8 -*-
"""ads_click.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buG4SUy1L3haN-chBcsxx1WPeCfhc3LA
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

ad=pd.read_csv("/content/advertising.csv")

ad.head()

lr=LogisticRegression()

ad.isnull().sum()

indep=ad[['Age','Area Income','Male']]
dep=ad['Clicked on Ad']

lr.fit(indep,dep)

lr.predict([[20,40000,0]])

sal=int(input("enter your income  "))
sex=int(input("if male enter 1 otherwise 0   "))
ag=int(input("enter your age  "))

print("your result is",lr.predict([[ag,sal,sex]]))

from sklearn.metrics import accuracy_score

pval=lr.predict(indep)
accuracy_score(dep,pval)