# -*- coding: utf-8 -*-
"""ads_selflearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dq0nlf7O5PtsmfGJJvwa6bHqPp1X_ODu
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = pd.read_csv("/content/advertising.csv")

df.head()

df = df[["Clicked on Ad", "Area Income", "Male", "Age", "Ad Topic Line"]].dropna()

le = LabelEncoder()
df["Male"] = le.fit_transform(df["Male"])

le = LabelEncoder()
df["Clicked on Ad"] = le.fit_transform(df["Clicked on Ad"])

X = df.drop(["Clicked on Ad", "Ad Topic Line"], axis=1)
y = df["Clicked on Ad"]

np.random.seed(42)
mask = np.random.rand(len(df)) < 0.5
df.loc[mask, "Clicked on Ad"] = -1

base_model = LogisticRegression()

self_training_model = SelfTrainingClassifier(base_model, criterion='k_best')

self_training_model.fit(X, y)

df["Predicted_Label"] = self_training_model.predict(X)

print(df.tail())