# -*- coding: utf-8 -*-
"""heart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TajchEgEFJfIMLzp9zUXDU1wjH1P-l02
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

heart=pd.read_csv("/content/heart.csv")
heart.head()

heart.isnull().sum()

heart.shape

X=heart.iloc[:,[0,4,5]].values

print(X)

heart.info()

wcss = []
for i in range(1,11):
  Kmeans = KMeans(n_clusters = i, init = 'k-means++',random_state=42)
  Kmeans.fit(X)
  wcss.append(Kmeans.inertia_)

k=KMeans(n_clusters=2,init='k-means++',random_state=0)
y=k.fit_predict(X)
print(y)

sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

sns.set()
plt.bar(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(X[y==0,0],X[y==0,1],s=50,c='red',label='High Risk')
plt.scatter(X[y==1,0],X[y==1,1],s=50,c='blue',label='Medium Risk')
plt.scatter(X[y==2,0],X[y==2,1],s=50,c='green',label='Less Risk')
plt.scatter(k.cluster_centers_[:,0],k.cluster_centers_[:,1],s=100,c='yellow',label='Centroids')
plt.title('Patient Clusters based on age and cholestrol')
plt.xlabel('blood pressure Level' )
plt.ylabel('cholestrol Level')
plt.legend()
plt.show()

sns.set()
plt.scatter(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()