# -*- coding: utf-8 -*-
"""k-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1IZBwVui7q2z24qhgT55xmh7o-BfP3K
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt

data ={
    'bp':[120,130,140,150,160,170,180,190,200,250],
    'cs':[200,210,240,260,280,300,320,330,340,350],
    'heart_risk':[0,0,0,0,1,1,1,1,1,1]
}

details=pd.DataFrame(data)

details.head()

a=details[['bp','cs']]
b=details['heart_risk']
details.head()

k=3
kd=KNeighborsClassifier(n_neighbors=k)
kd.fit(a,b)

new_data=np.array([[210,250]])
prediction=kd.predict(new_data)
if prediction==0:
  print("No risk")
else:
  print("At risk")