# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9XvOv0RJvySm97o3n-D7sroNlBy4xss

**TO IMPORT**
"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()

"""**DATA GIVEN**"""

t=[[5],[7],[12],[16],[20]]
m=[40,120,180,210,240]
LR.fit(t,m)

""" **TO PREDICT**"""

LR.predict([[19]])