# -*- coding: utf-8 -*-
"""retina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVgAU4Qn5xNOPk3rCCKHyoPC3vnWZ1Rl
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from google.colab import drive
drive.mount('/content/drive')

IMG_SIZE = 224
BATCH_SIZE = 32

model.save('/content/drive/MyDrive/retina.h5')

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt #visualisation
import numpy as np
model =load_model('/content/drive/MyDrive/retina.h5')
print("Model Loaded")

img_array=image.img_to_array(img)
img_array=np.expand_dims(img_array,axis=0)
img_array /= 255.
prediction = model.predict(img_array)
print(prediction)

train_datagen =ImageDataGenerator(rescale=1./255,validation_split=0.2)
train_generator = train_datagen.flow_from_directory("/content/drive/MyDrive/retina",target_size=(IMG_SIZE, IMG_SIZE),batch_size=BATCH_SIZE,class_mode='binary',subset='training')

val_generator = train_datagen.flow_from_directory("/content/drive/MyDrive/retina",target_size=(IMG_SIZE, IMG_SIZE),batch_size=BATCH_SIZE,class_mode='binary',subset='validation')

model = keras.Sequential([
 layers.Conv2D(32, (3, 3), activation='relu',
input_shape=(IMG_SIZE, IMG_SIZE, 3)),
 layers.MaxPooling2D((2, 2)),
 layers.Conv2D(64, (3, 3), activation='relu'),
 layers.MaxPooling2D((2, 2)),
 layers.Conv2D(128, (3, 3), activation='relu'),
 layers.MaxPooling2D((2, 2)),
 layers.Flatten(),
 layers.Dense(128, activation='relu'),
 layers.Dense(1, activation='sigmoid')
])
model.summary()
Model: "sequential"

model.compile(optimizer='adam', loss='binary_crossentropy',
metrics=['accuracy'])
model.fit(train_generator, epochs=5, validation_data=val_generator,
batch_size= BATCH_SIZE)

from keras.preprocessing import image
import matplotlib.pyplot as plt
test_image_path="/content/drive/MyDrive/retina/no/2329_left.jpg"
img=image.load_img(test_image_path,target_size=(IMG_SIZE,IMG_SIZE))
plt.imshow(img)
plt.axis()
plt.show()

if prediction >= 0.5:
 print("patient have problem in retina.")
else:
 print("patient do not have problem in eye.")