# -*- coding: utf-8 -*-
"""self_dia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJJcw73YZOt1hdR1tyUFH2dIFwan247z
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = pd.read_excel("/content/diabetes.xlsx")

df.head()

df = df[["class", "insu", "age", "pres", "mass"]].dropna()

df.head()

X = df.drop("class", axis=1)
y = df["class"]

np.random.seed(42)
mask = np.random.rand(len(df)) < 0.5
df.loc[mask, "class"] = -1

base_model = LogisticRegression()

self_training_model = SelfTrainingClassifier(base_model, criterion='k_best')

self_training_model.fit(X, y)

df["Predicted_Label"] = self_training_model.predict(X)

print(df.head(20))