# -*- coding: utf-8 -*-
"""SelfLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-iOQfmmrbfdOAFiriL4cKoRpyn73-1O
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = pd.read_csv("/content/Titanic Data.csv")

df = df[["Survived", "Pclass", "Sex", "Age", "Fare"]].dropna()

df.head()

le = LabelEncoder()
df["Sex"] = le.fit_transform(df["Sex"])

X = df.drop("Survived", axis=1)
y = df["Survived"]

np.random.seed(42)
mask = np.random.rand(len(df)) < 0.5
df.loc[mask, "Survived"] = -1

base_model = LogisticRegression()

self_training_model = SelfTrainingClassifier(base_model, criterion='k_best')

self_training_model.fit(X, y)

df["Predicted_Label"] = self_training_model.predict(X)

print(df.head(20))