# -*- coding: utf-8 -*-
"""sns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112mJqe-WpAB5izFfPTfelFW9qYPAcCKO
"""

import seaborn as sns
import matplotlib.pyplot as plt

tips=sns.load_dataset('tips')

tips=sns.load_dataset('tips')
sns.barplot(x='total_bill',y='tip',data=tips)
plt.title('bar Plot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

tips=sns.load_dataset('tips')
sns.lineplot(x='total_bill',y='tip',data=tips)
plt.title('line Plot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

tips=sns.load_dataset('tips')
sns.boxplot(x="day",y="total_bill",data=tips)
plt.title('box Plot')
plt.xlabel('Day')
plt.ylabel('Total Bill')
plt.show()

import seaborn as ss
import matplotlib.pyplot as plt
tips=ss.load_dataset("tips")
ss.violinplot(x="day",y="total_bill",data=tips)
plt.title("average total bill by day")
plt.xlabel("day of the week")
plt.ylabel("total bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset('iris')
sns.pairplot(iris, hue='species')
plt.show()

import seaborn as ss
import matplotlib.pyplot as plt
tips=ss.load_dataset("tips")
ss.jointplot(x="total_bill", y="tip", data=tips, kind="hex")
plt.title=("average total bill by day")
plt.xlabel("day of the week")
plt.ylabel("total bill")
plt.show()

import seaborn as ss
import matplotlib.pyplot as plt
titanic=ss.load_dataset("titanic")
ss.countplot(x="class",data=titanic)
plt.xlabel("passenger class")
plt.ylabel("count")
plt.show()

sns.barplot(x="day",y="total_bill",data=tips)
plt.xlabel('DAY')
plt.ylabel('TOTAL BILL')
plt.show()

iris=sns.load_dataset('iris')
# Drop the non-numeric 'species' column
correlation_matrix=iris.drop('species', axis=1).corr()
sns.heatmap(correlation_matrix,annot=True,cmp="coolwarm")
plt.title('Heatmap')
plt.xlabel('Features')
plt.ylabel('Features')
plt.show()

sns.scatterplot(x='total_bill',y='tip',data=tips)
plt.title('Scatter Plot')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()