# -*- coding: utf-8 -*-
"""socilamedia_ads.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydPACjOM74okXpaogOzxvBSOJkMr_rgG

**Predict if a user will click on an ad
based on age, salary, and gender.**
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

ads=pd.read_csv("/content/Social_Network_Ads.csv")

lr=LogisticRegression()

ads.head()

ads.isnull().sum()

from sklearn.preprocessing import StandardScaler

ads['Gender']=ads['Gender'].map({'Male':1,'Female':0})

ads.head()

indep=ads[['Gender','Age','EstimatedSalary']]
dep=ads['Purchased']

lr.predict([[0,25,60000]])

lr.fit(indep,dep)

LR=StandardScaler()