# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leXMbJKFjaKQ6XuqxK9QIdnwf-XN5YQZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

titanic=pd.read_csv("/content/Titanic_logic_survival_rate.csv")

titanic.head()

titanic.isnull().sum()

titanic.isnull().sum()

from sklearn.preprocessing import LabelEncoder

LR=LabelEncoder()

titanic['Gender']=LR.fit_transform(titanic['Sex'])

titanic.head()

titanic['Embarked']=LR.fit_transform(titanic['Embarked'])

titanic.head()

indep=titanic[['Pclass','Gender','Age','Embarked']]
dep=titanic['Survived']

lr.fit(indep,dep)

lr.predict([[1,0,25,2]])

titanic.info()

titanic.dropna(inplace=True)